#!/bin/sh

MACHINE_AGENT_HOME=/opt/appdynamics/machine-agent
JAVA_HOME=/opt/appdynamics/machine-agent/jre
MACHINE_AGENT_USER=root
PIDFILE=/var/run/appdynamics/appdynamics-machine-agent

# Note: If you would like to change MACHINE_AGENT_USER you must also ensure that
# the PIDFILE and MACHINE_AGENT_HOME directories both have write permissions for the
# new MACHINE_AGENT_USER (by using the chown command or copying the machine agent
# folders into a directory where the MACHINE_AGENT_USER has write permissions
# (and likewise updating the MACHINE_AGENT_HOME path)
